### ISSUE TITLE
News for people sponsoring via bountysource

### ISSUE THREAD

**Issue by ganwell** [neovim/neovim.github.io#141]
Hi

I like to ask you to write something about what is done using the money we sponsor. The last official news was in December 2015. It doesn't have to be too often, every 4 month would be sufficient. I know there is some news about the project in general on twitter, but we sponsor the work of @tarruda, so I am curious what is going on there.

Best,
    Jean-Louis

**Comment by justinmk** [comment]
There is a draft of the [newsletter](https://github.com/neovim/neovim.github.io/pull/136). I keep getting sidetracked by "fixing one last bug", so it's not published, but, it's mostly done and available since July.

I removed @tarruda's name from the [salt page](https://salt.bountysource.com/teams/neovim). The salary is intended to fund any experienced core contributor who can meet the obligations of the fundraiser (current ~2 days per week).

I plan to draw the salary for November/December. Outside of that I asked @ZyX-I to accept the salary because of the major work needed in [#4411](https://github.com/neovim/neovim/pull/4411) and [#5119](https://github.com/neovim/neovim/pull/5119).

**Comment by ganwell** [comment]
@justinmk Thanks a lot for the update. I now understand better.

**Comment by justinmk** [comment]
Newsletter was published. We'll do another one for the 0.2. release as well.
