### ISSUE TITLE
update the sponsor page

### ISSUE THREAD

**Issue by teto** [neovim/neovim.github.io#218]
https://neovim.io/sponsors/ still shows bountysource but we now prefer donations via github sponsor/opencollective so better to put these in front. 

In case we do it, we may need to notify the sponsors ? to notify they can subscribe with github instead or if they want to cancel because the sponsorship will be less visible

**Comment by justinmk** [comment]
this was done

**Comment by XVilka** [comment]
@justinmk by the way, maybe combine names of the original BountySource backers into groups? It will make the page less unwieldy without reducing the amount of information. Since the BountySource campaign will not update anymore, no need to use their autogenerated table, and simply can be summarized by combining names into multiple categories - by the amount donated.
