### ISSUE TITLE
Move to SSL via Cloudflare

### ISSUE THREAD

**Issue by cweagans** [neovim/neovim.github.io#86]
We don't have anything overly sensitive on the Neovim website, but that shouldn't stop us from enabling SSL. IIRC, we talked about moving to CloudFlare, which would also allow us to enable the Universal SSL service in the CloudFlare control panel. @jdavis, I think I recall you saying something about CloudFlare?

**Comment by justinmk** [comment]
cloudflare was mentioned as a solution to the CNAME situation. https://github.com/neovim/neovim.github.io/issues/66#issuecomment-51380761

**Comment by jdavis** [comment]
Yup. I already moved it to Cloudflare and SSL is already turned on: https://neovim.org/

If we wanted it to be the default, I'd just have to setup a page rule from http -> https.

**Comment by fwalch** [comment]
:+1: for HTTPS by default. Some links that only use HTTP need to be fixed (e.g. Google Fonts), otherwise Firefox warns that "some unencrypted elements on this website have been blocked" when visiting the HTTPS page.

**Comment by justinmk** [comment]
> Some links that only use HTTP need to be fixed 

It's good practice to use "protocol relative" urls  http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by fwalch** [comment]
@justinmk: Actually, the page you linked to doesn't recommend "protocol relative", but just unconditionally using HTTPS:

> Now that SSL is encouraged for everyone and doesn’t have performance concerns, this technique is now an anti-pattern. If the asset you need is available on SSL, then always use the https:// asset.

**Comment by cweagans** [comment]
Yeah, but for local development, it's nicer to have things pulled in on the same protocol. +1 for protocol relative URLs.

**Comment by jdavis** [comment]
I'll add the page rule to only use HTTPS. Then I can fix up the loading of the resources tonight unless someone beats me to it with a PR.

**Comment by fwalch** [comment]
https://neovim.io now shows a certifcate error. Can we set up HTTPS for the new URL?

**Comment by jdavis** [comment]
All of this is in the hands of Thiago now. He controls the domain and DNS for both.

**Comment by fwalch** [comment]
Ping @tarruda.

**Comment by tarruda** [comment]
As explained by [this blog post](https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it), using cloudflare SSL is not really a secure approach because the connection between github and cloudflare is still unencrypted, a "man in the middle" could simply sit between cloudflare and github to change the served content. This would be even worse than plain http since users would have a false sense of security.

Maybe we can force fully secure connection to neovim.{org,io} while still using github pages as a host, but I'm not sure this would work:

- Setup a web server(already got the digital ocean VPS)
- Serve a single page containing an iframe pointing to https://neovim.github.io(removing the CNAME file so no redirection happens). This page would need some javascript to forward the path to the iframe URL.
- Buy a SSL certificate for neovim.io, and redirect it to the VPS ip

**Comment by cweagans** [comment]
-1 for running our own web infrastructure. That's led to some poor decisions in the Drupal community. 

You can just use the https version of the GH pages site as the cloudflare origin. Problem solved.

**Comment by cweagans** [comment]
Also, I'd be more concerned if we were a banking website or something. Its not a high value target to MITM. I don't think we have anything to worry about.

**Comment by justinmk** [comment]
> -1 for running our own web infrastructure. 

Agreed. Please don't do this.

**Comment by tarruda** [comment]
> You can just use the https version of the GH pages site as the cloudflare origin. Problem solved.

According to the blog post I linked this isn't possible yet:

> Until GitHub Pages or CloudFlare fix things, you'll only be able to encrypt the connection between the user and CloudFlare. The connection between CloudFlare and GitHub Pages will need to remain in plaintext, using CloudFlare's "Flexible SSL" option. For more information on why this is the case, read these comments that lay out how it works.

Though I admit I did not investigate this much.

If it's possible to have a fully encrypted connection between visitors and github pages, then using cloudflare ssl for neovim.io is a good approach. If not, there's nothing to gain by using SSL since cloudflare <-> github connection is still unencrypted. In fact it would be even worse since we would be giving a false sense of security to neovim.io visitors(which can for example, disable javascript for non-ssl websites)

**Comment by cweagans** [comment]
https://neovim.github.io redirects to the CNAME in the repo. The HTTPS version is live - we just get redirected away from it. We'd have to remove the cname file in the repo to verify.

**Comment by tarruda** [comment]
I have moved neovim to my cloudflare account and it is using ssl
